// Switches which backend the frontend talks to by (re)writing .env.local,
// which Next.js loads with the highest precedence in `next dev`.
//
//   npm run env:local     → talk to local backend  (removes .env.local → .env.development wins)
//   npm run env:staging   → talk to the configured staging API
//   npm run env:prod      → talk to production
//
// .env.local is gitignored, so this never affects committed files.
import { writeFileSync, rmSync } from "node:fs";

// Single source of truth for each environment's API base URL.
// `null` = no override (fall back to .env.development → http://localhost:4000/api).
const ENVIRONMENTS = {
  local: null,
  staging: process.env.MOODIES_STAGING_API_URL ?? "",
  prod: process.env.MOODIES_PROD_API_URL ?? "",
};

const name = process.argv[2];

if (!(name in ENVIRONMENTS)) {
  console.error(`Usage: node scripts/use-env.mjs <${Object.keys(ENVIRONMENTS).join(" | ")}>`);
  process.exit(1);
}

const url = ENVIRONMENTS[name];

if (name !== "local" && !url) {
  const variable = name === "staging" ? "MOODIES_STAGING_API_URL" : "MOODIES_PROD_API_URL";
  console.error(`Set ${variable} before switching to ${name}.`);
  process.exit(1);
}

if (url === null) {
  rmSync(".env.local", { force: true });
  console.log("✅ Switched to LOCAL — removed .env.local (using .env.development → http://localhost:4000)");
} else {
  writeFileSync(
    ".env.local",
    `# Auto-generated by scripts/use-env.mjs — active environment: ${name}\n` +
      `# Run "npm run env:local" to go back to the local backend.\n` +
      `NEST_API_URL="${url}"\n` +
      `NEXT_PUBLIC_API_URL="${url}"\n`,
  );
  console.log(`✅ Switched to ${name.toUpperCase()} → ${url}`);
}

console.log("⚠️  Restart the dev server (Ctrl+C, then npm run dev) to apply.");
