services:
  postgres-dev:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin@123
      POSTGRES_DB: moodies_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - moodies-net

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    depends_on:
      - postgres-dev
      - mongo
    ports:
      - "4000:4000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    depends_on:
      - server
    ports:
      - "3000:3000"

networks:
  moodies-net:

volumes:
  pgdata:
  mongodata:
