// prisma/seed/moods.seed.ts
import type { PrismaClient } from '@prisma/client';
import { Prisma } from '@prisma/client';

export async function seedMoods(prisma: PrismaClient) {
  // TMDB Genre IDs mapping reference:
  // Comedy: 35, Action: 28, Horror: 27, Romance: 10749, Drama: 18, Thriller: 53
  // Animation: 16, Family: 10751, Adventure: 12, Mystery: 9648, Crime: 80
  // Fantasy: 14, Science Fiction: 878, Documentary: 99, History: 36, Music: 10402

  const moods = [
    {
      name: 'Happy',
      color: '#FFD700',
      icon: 'smile',
      description: 'Feel-good content to brighten your day',
      keywords: ['comedy', 'feel-good', 'uplifting', 'cheerful', 'positive'],
      tmdbGenres: [35, 16, 10751, 12],
      valence: 0.8,
      arousal: 0.5,
      isActive: true,
    },
    {
      name: 'Thrilling',
      color: '#FF6B35',
      icon: 'zap',
      description: 'Heart-pounding adventures and excitement',
      keywords: ['action', 'adventure', 'exciting', 'intense', 'adrenaline'],
      tmdbGenres: [28, 53, 12, 80],
      valence: 0.6,
      arousal: 0.9,
      isActive: true,
    },
    {
      name: 'Horror',
      color: '#8B0000',
      icon: 'skull',
      description: 'Spine-chilling scares and supernatural thrills',
      keywords: ['scary', 'frightening', 'supernatural', 'suspense', 'terror'],
      tmdbGenres: [27, 9648],
      valence: -0.3,
      arousal: 0.8,
      isActive: true,
    },
    {
      name: 'Romantic',
      color: '#FF69B4',
      icon: 'heart',
      description: 'Love stories and heartwarming connections',
      keywords: ['love', 'romance', 'relationship', 'heartwarming', 'emotional'],
      tmdbGenres: [10749, 18],
      valence: 0.7,
      arousal: 0.3,
      isActive: true,
    },
    {
      name: 'Chill',
      color: '#20B2AA',
      icon: 'wind',
      description: 'Relaxing content for unwinding',
      keywords: ['relaxing', 'calm', 'peaceful', 'soothing', 'meditative'],
      tmdbGenres: [18, 36, 99],
      valence: 0.3,
      arousal: -0.5,
      isActive: true,
    },
    {
      name: 'Dark',
      color: '#2F4F4F',
      icon: 'moon',
      description: 'Mysterious and thought-provoking narratives',
      keywords: ['mysterious', 'psychological', 'complex', 'introspective', 'noir'],
      tmdbGenres: [9648, 53, 80, 878],
      valence: -0.2,
      arousal: 0.4,
      isActive: true,
    },
    // 🌟 New moods
    {
      name: 'Epic',
      color: '#8A2BE2',
      icon: 'crown',
      description: 'Grand adventures and fantasy worlds',
      keywords: ['fantasy', 'epic', 'heroic', 'legendary', 'mythical'],
      tmdbGenres: [14, 12, 28, 878],
      valence: 0.5,
      arousal: 0.8,
      isActive: true,
    },
    {
      name: 'Inspirational',
      color: '#32CD32',
      icon: 'star',
      description: 'Stories that uplift and motivate',
      keywords: ['inspiring', 'emotional', 'true story', 'motivating', 'heartfelt'],
      tmdbGenres: [18, 36, 99],
      valence: 0.9,
      arousal: 0.6,
      isActive: true,
    },
    {
      name: 'Nostalgic',
      color: '#FFB347',
      icon: 'clock',
      description: 'Classic tales and retro vibes',
      keywords: ['classic', 'retro', 'nostalgic', 'childhood', 'old school'],
      tmdbGenres: [35, 16, 10751, 10402],
      valence: 0.6,
      arousal: 0.4,
      isActive: true,
    },
    {
      name: 'Sad',
      color: '#4682B4',
      icon: 'cloud-rain',
      description: 'Emotional and tear-jerking stories',
      keywords: ['sad', 'emotional', 'tragic', 'heartbreaking', 'drama'],
      tmdbGenres: [18, 10749],
      valence: -0.5,
      arousal: 0.3,
      isActive: true,
    },
    {
      name: 'Funny',
      color: '#FFB6C1',
      icon: 'laugh',
      description: 'Lighthearted comedies to make you laugh',
      keywords: ['funny', 'hilarious', 'comedy', 'parody', 'satire'],
      tmdbGenres: [35, 10751, 16],
      valence: 0.9,
      arousal: 0.6,
      isActive: true,
    },
    {
      name: 'Documentary',
      color: '#708090',
      icon: 'book',
      description: 'Real-world stories and factual content',
      keywords: ['documentary', 'true', 'educational', 'informative', 'real'],
      tmdbGenres: [99, 36],
      valence: 0.4,
      arousal: 0.2,
      isActive: true,
    },
    {
      name: 'Melancholy',
      color: '#708090',
      icon: 'cloud',
      description: 'Bittersweet, deep, and reflective stories',
      keywords: ['sad', 'tragic', 'thoughtful', 'poignant'],
      tmdbGenres: [18, 10749],
      valence: -0.4,
      arousal: -0.2,
      isActive: true,
    },
    {
      name: 'Patriotic',
      color: '#B22222',
      icon: 'flag',
      description: 'War, history, and tales of sacrifice',
      keywords: ['war', 'history', 'sacrifice', 'bravery'],
      tmdbGenres: [36, 10752, 99],
      valence: 0.2,
      arousal: 0.7,
      isActive: true,
    },
    {
      name: 'Musical',
      color: '#FF1493',
      icon: 'music',
      description: 'Song, dance, and musical journeys',
      keywords: ['music', 'song', 'dance', 'performance'],
      tmdbGenres: [10402, 35, 10751],
      valence: 0.8,
      arousal: 0.6,
      isActive: true,
    }, {
      name: 'Adventurous',
      color: '#1E90FF',
      icon: 'compass',
      description: 'Journey into the unknown with epic quests and discoveries',
      keywords: ['adventure', 'explore', 'journey', 'quest'],
      tmdbGenres: [12, 14, 878],
      valence: 0.6,
      arousal: 0.8,
      isActive: true,
    },
    {
      name: 'Wholesome',
      color: '#FFE4B5',
      icon: 'sun',
      description: 'Heartwarming stories for the whole family',
      keywords: ['family', 'wholesome', 'warm', 'kind', 'pure'],
      tmdbGenres: [10751, 16, 35],
      valence: 0.9,
      arousal: 0.3,
      isActive: true,
    },
    {
      name: 'Mind-Bending',
      color: '#4B0082',
      icon: 'brain',
      description: 'Twists, puzzles, and stories that bend reality',
      keywords: ['mystery', 'sci-fi', 'psychological', 'twist'],
      tmdbGenres: [9648, 878, 53],
      valence: 0.2,
      arousal: 0.7,
      isActive: true,
    },
    {
      name: 'Gritty',
      color: '#696969',
      icon: 'shield',
      description: 'Dark, raw, and street-level narratives',
      keywords: ['crime', 'gritty', 'urban', 'raw'],
      tmdbGenres: [80, 18, 53],
      valence: -0.3,
      arousal: 0.6,
      isActive: true,
    },
    {
      name: 'Sci-Fi',
      color: '#00CED1',
      icon: 'rocket',
      description: 'Exploration of technology, space, and the future',
      keywords: ['sci-fi', 'space', 'technology', 'future'],
      tmdbGenres: [878, 12, 14],
      valence: 0.5,
      arousal: 0.7,
      isActive: true,
    },
    {
      name: 'Western',
      color: '#CD853F',
      icon: 'cowboy',
      description: 'Cowboys, duels, and frontier justice',
      keywords: ['western', 'cowboy', 'frontier', 'gunslinger'],
      tmdbGenres: [37, 28, 12],
      valence: 0.4,
      arousal: 0.6,
      isActive: true,
    },
    {
      name: 'War & Sacrifice',
      color: '#800000',
      icon: 'crosshair',
      description: 'Stories of bravery, sacrifice, and the cost of war',
      keywords: ['war', 'sacrifice', 'soldier', 'battle'],
      tmdbGenres: [10752, 36, 99],
      valence: -0.1,
      arousal: 0.9,
      isActive: true,
    },
    {
      name: 'Cozy',
      color: '#FFDEAD',
      icon: 'mug-hot',
      description: 'Comforting stories to curl up with',
      keywords: ['cozy', 'comfort', 'gentle', 'warm'],
      tmdbGenres: [35, 10751, 16],
      valence: 0.7,
      arousal: 0.2,
      isActive: true,
    },
    {
      name: 'Experimental',
      color: '#FF4500',
      icon: 'beaker',
      description: 'Artsy, indie, and unconventional storytelling',
      keywords: ['artsy', 'indie', 'experimental', 'avant-garde'],
      tmdbGenres: [10770, 18, 99],
      valence: 0.3,
      arousal: 0.4,
      isActive: true,
    },
    {
      name: 'Empowering',
      color: '#ADFF2F',
      icon: 'fist',
      description: 'Stories of resilience, empowerment, and overcoming odds',
      keywords: ['empowering', 'uplifting', 'motivating', 'strong'],
      tmdbGenres: [18, 36, 10752],
      valence: 0.8,
      arousal: 0.7,
      isActive: true,
    },
    {
      name: 'Philosophical',
      color: '#708090',
      icon: 'book-open',
      description: 'Deep stories that provoke thought and reflection',
      keywords: ['philosophy', 'existential', 'deep', 'reflective'],
      tmdbGenres: [18, 99, 9648],
      valence: 0.1,
      arousal: 0.3,
      isActive: true,
    },
  ];

  for (const moodData of moods) {
    await prisma.mood.upsert({
      where: { name: moodData.name },
      update: {}, // keep unchanged if it already exists
      create: {
        name: moodData.name,
        color: moodData.color,
        icon: moodData.icon,
        description: moodData.description,
        keywords: moodData.keywords,
        tmdbGenres: moodData.tmdbGenres,
        valence: new Prisma.Decimal(moodData.valence),
        arousal: new Prisma.Decimal(moodData.arousal),
        isActive: moodData.isActive,
      },
    });
    console.log(`Seeded mood: ${moodData.name}`);
  }
}